name: skycord

dependencies:
  nyxx:
    git:
      url: git://github.com/l7ssha/nyxx.git
      ref: 8eb33737751b9858059d5fd0f975669cb3307465
#  skyscrapeapi: ^4.0.0+2
  skyscrapeapi:
    git: https://github.com/ClearHall/SkyScrapeAPI.git
  hive: ^1.4.1+1
  logging: ^0.11.4

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0
